blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.renderPosts, name="posts"),
    path("<int:post_id>", views.post_detail, name="post_detail"),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(default=datetime.date.today)

    def __str__(self) -> str:
        return self.title

portfolio/models.py
from django.db import models

from django.db.models.fields import CharField, TextField, DateField, URLField
from django.db.models.fields.files import ImageField
from datetime import date

class Project(models.Model):
    title = CharField(max_length=100)
    description = TextField()
    image = ImageField(upload_to="portfolio/images")
    url = URLField(blank=True)
    date = DateField(default=date.today)

    def __str__(self) -> str:
        return self.title

blog/views.py
from django.shortcuts import render
from .models import Post

def renderPosts(requests):
    total_posts = Post.objects.count()
    posts = Post.objects.order_by("-date")
    return render(request, "blog.html", {"posts":posts, "total_posts": total_posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "post_detail.html", {"post": post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, "home.html", {"projects": projects})

blog/templates/blog.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="fs-2">Posts</h1>
<h3>There are {{total_posts}} post{{total_posts|pluralize}}</h3>

{% for post in posts %>

<div class="py-3">

	<div class="card card-body bg-black">
		<div class="row">

			<div class="col-3">
				<img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">

			</div>
			<div class="col-9">

				<h1>{{post.title}}</h1>
				<p>{{post.description|striptags|truncatechars:100}}</p>
				<p>{{post.date|date:'M d Y'|upper}}</p>

				<a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
			</div>
		</div>
	</div>
</div>

{% endfor %}

{% endblock %}

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">

	<h1>{{post.title}}</h1>
	<h2 class="my-h2 h5 text-muted">{{post.date|date:'F jS Y'}}</h2>

	<img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">


	<div class="my-4">
	
	{{post.description|safe}}
	</div>
</div>

{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}
<!-- Hero Section -->
<header>
	<div class="row flex-lg-row-reverse align-items-center g-5 py-5">
		<div class="col-md-8 col-sm-8 col-lg-6">
			<img src="{% static 'portfolio/amvpro.jpg' %}" class="d-block mx-md-auto img-fluid" alt="Hero section" loading="lazy"/>
		</div>
		<div class="col-lg-6">
			<h1 class="display-5 fw-bold lh-1 mb-3">Alexander Morales Villatoro</h1>
			<p class="lead">Software engineer with over 20 years of experience in infrastructure engineering and IT team management. Used to work with Infrastructure as Code, Agile methodologies, change management and business transformation systems. Get used to handling Ruby, Python and Bash Scripting based code, Linux based Infrastructure on Bare Metal Service Providers such as VMWare and Proxmox, as well as Cloud Providers such as GCP and AWS.</p>
			<div class="d-grid gap-2 d-md-flex justify-content-md-start">
				<a href="{% static 'portfolio/CV_AMV.zip'%}" class="btn btn-primary" role="button" aria-pressed="false">Download my resume</a>
			</div>
		</div>
	</div>
</header>
<!-- Portfolio Section -->
<div class="row my-4 text-justify">

	<h3>Experience</h3>
	<p class="lead">Over the years I has been working on several projects, including Management and Software Development, below you may find some of the project and the position I was involved on, including but not limiting to: Management Projects, Softwre Engineering Projects and Hobbie related projects</p>
	
	{% for project in projects %}
	<div class="col-md-4">
		<div class="card card-project">
			<img src="{{ project.image.url }}" class="card-img-top" />

			<div class="card-body">

				<h2>{{ project.title }}</h2>
				<p>{{ project.description|linebreaks}}</p>

				{% if project.url %}
				<a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="__blank" rel="noreferrer">See project 
					details</a>
				{% endif %}
			</div>
		</div>
	</div>
	{% endfor %}
</div>


{% endblock %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Alexander Morales Site</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>


<body>
  {% include 'partials/navbar.html' %}
  <div class="container p-4">
    {% block content %}
    {% endblock %}
  </div>

</body>


</html>

portfolio/templates/partials/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container-fluid">
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse justify-content-md-center" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="https://github.com/runemalops" target="_blank">Runemalops</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
				</li>
				<li class="nav-item d-flex align-items-center">
					<a class="btn btn-primary btn-sm" href="{% static 'portfolio/CV_AMV.zip'%}" %}" target="_blank">Download CV</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
<!-- Navbar -->